### ISSUE TITLE
(Journey) AJ1: User Donates

### ISSUE THREAD

**Issue by grayside** [GoogleCloudPlatform/emblem#21]
## Description

As a contributor, I make a contribution to an identified giving campaign.

Note: No financial transaction will take place.

## Phase 1 Requirements

Completing all requirements does not mean this journey can be considered "healthy", and closed, but it is an indicator that we haven't identified other tasks to be done.

* [x] User can submit a form to create a donation to a campaign via the website
* [x] API allows creation of a donation that will be recorded to the database.
* [x] API has a basis to trust the named donor

## Related Decision Records

*<This section will be filled out as this journey's tasks pass through design>*

## Possible Future Enhancements

* Recurring contribution
* Deferred contribution
* Payment authorization workflow
