### ISSUE TITLE
(Journey) AJ2: Campaign Discovery

### ISSUE THREAD

**Issue by grayside** [GoogleCloudPlatform/emblem#22]
## Description

As a potential contributor, in order to find an appealing giving campaign, I want to review a list of all active campaigns and read campaign details to make a decision.

## Phase 1 Requirements

Completing all requirements does not mean this journey can be considered "healthy", and closed, but it is an indicator that we haven't identified other tasks to be done.

* [x] View a list of active campaigns
* [x] Click to view dedicated page with campaign details
* [x] Start a donation from campaign view in list or detail page
* [x] API can serve a list of campaigns on request

## Related Decision Records

*<This section will be filled out as this journey's tasks pass through design>*

## Possible Future Enhancements

* Page through listing of many campaigns, MVP can assume a limited number of campaigns until Campaign Creation is enabled via the UI.
* Search experience to discover campaigns by title
* Sorting controls, such as alphabetical by title vs. donations to date
