### ISSUE TITLE
(Journey) SJ2: Cloud-based Software Evolution

### ISSUE THREAD

**Issue by grayside** [GoogleCloudPlatform/emblem#24]
## Description

As a technical practitioner, I want to understand how to manage software change to account for the evolution of Google Cloud Products, industry recommended practices, language & framework features, application requirements, and the people on my team.

## Phase 1 Requirements

Completing all requirements does not mean this journey can be considered "healthy", and closed, but it is an indicator that we haven't identified other tasks to be done.

* [x] Contributing guidelines on decision records are in CONTRIBUTING.md
* [x] An ADR Log is in place to capture decisions.
* [ ] Our tech stack is clearly documented
* [x] Decide as a team the initial practice is sufficient and sustainable, or fast-follow to phase 2, perhaps pulling from the future enhancements.

## Related Decision Records

*<This section will be filled out as this journey's tasks pass through design>*

## Possible Future Enhancements

* Adopt a more mature decision record practice such as [MADR format](https://adr.github.io/madr/) (not the associated tool, which is archived) or https://github.com/thomvaill/log4brains
* Build topical views of decision records to support exploring the evolution of a specific concept such as "security" or "delivery". This might also be in the form of retrospective blog posts.
* Build automation around decision record creation, such as requiring them in PRs with/without a certain label or automatically filing a task to create a decision record if a PR is merged without one.
* Automate the association of decision records with releases or User Journeys
