### ISSUE TITLE
(Journey) SJ3: Deploy a New Instance

### ISSUE THREAD

**Issue by grayside** [GoogleCloudPlatform/emblem#25]
## Description

As a technical practitioner, in order to experiment with the Emblem app, I want to easily and quickly deploy it using my own account. This should be completed within 15 minutes and set a clear expectation of wait time.

Note: 15 minutes is a ceiling and we should expect drop-off of completion or follow-up exploration beyond 5 minutes.

## Phase 1 Requirements (v0.3.0)

* [ ] Requiring only an empty project, a single script can be executed to bootstrap the project.
* [ ] Deployment completes within 15 minutes, prefer 5-10 minutes to ensure we have space in the future

## Phase 2 Requirements

* [ ] Deploy with Cloud Shell makes a push-button option available
* [ ] Deployment completion provides clear prompts to next steps, such as directing to filtered log views or launching a NEOS tutorial
* [ ] We have deployment telemetry indicating how many unique deployed instances have been launched

## Related Decision Records

*<This section will be filled out as this journey's tasks pass through design>*

## Possible Future Enhancements

* TBD
