### ISSUE TITLE
(Journey) SJ4: Deploy a change

### ISSUE THREAD

**Issue by grayside** [GoogleCloudPlatform/emblem#26]
## Description

As an application developer, I want to know how to set up a continuous delivery pipeline from source control to my serverless environment and know how to detect problems before they affect my entire user base. 

## Phase 1 Requirements

Completing all requirements does not mean this journey can be considered "healthy", and closed, but it is an indicator that we haven't identified other tasks to be done.

* [x] After first setting up the project, it is possible to deploy infrastructure or code updates manually
* [x] When the `main` branch is updated, we are able to deliver updates based on code change
* [ ] Delivery of code changes includes testing to make sure the change did not create an outage

## Related Decision Records

*<This section will be filled out as this journey's tasks pass through design>*

## Possible Future Enhancements

* Canary deployments
