### ISSUE TITLE
(Journey) SJ5: Rollback a bad change

### ISSUE THREAD

**Issue by grayside** [GoogleCloudPlatform/emblem#27]
## Description

As a release manager, in order to recover from a bad deployment, I want to know how to revert my application to the previous known working release.

## Phase 1 Requirements

* [ ] If a deploy of the Website fails, we can automatically/quickly restore functionality by remotely executing a pre-defined operation.
* [ ] If a deploy of the Content API is found to have created an outage, we can quickly restore functionality by remotely executing a pre-defined operation.
* [ ] This process is extensible to add support for state/schema management
* [ ] There is documentation on how & when to perform a rollback

## Related Decision Records

Decisions to make include:
* How will rollback happen for Cloud Run?
* How will rollback happen for Cloud Functions?
* What pieces are automatic? Is human action or approval always required?

## Possible Future Enhancements

* Add schema management to the rollback process
* Add notifications, such as filing a GitHub issue about the rollback.
