### ISSUE TITLE
(Journey)  SJ10: Create a local development environment

### ISSUE THREAD

**Issue by grayside** [GoogleCloudPlatform/emblem#42]
## Description

As a technical practitioner, in order to run the application locally, I want to know how to set up my local development environment within 15 minutes of getting started.

## Phase 1 Requirements

* [ ] Direct command-line way to spin up all necessary services to run locally. This might mean using "feature toggles" to use in-memory storage or locally running backing services such as a database.
* [ ] Method in VSCode to set up services, along the lines as the CLI requirement
* [ ] Out-of-box configuration for common git and vscode behavior, included such things as recommended vscode extensions for our tech stack and gitattributes
* [ ] The local setup is clearly documented without assuming existing tech stack knowledge

## Related Decision Records

* Why using vscode as our "default" IDE?

## Possible Future Enhancements

TBD
