### ISSUE TITLE
(Journey) SJ17: Limit blast radius of a security exploit

### ISSUE THREAD

**Issue by grayside** [GoogleCloudPlatform/emblem#45]
## Description

As an operations engineer, in order to ensure a security exploit will have limited impact on my Google Cloud resources, I want to know how to apply the principle of least privilege confidently in a confusing IAM landscape.

## Phase 1 Requirements

* [ ] Each component has at least one dedicated service account
* [ ] Each service account has the minimum roles necessary to perform work
* [ ] Editor/Owner role should never be used, except if necessary (such as with Terraform)
* [ ] IAM permissions should be scoped to individual resources, for example: accessing a specific secret, invoking a specific service.

## Related Decision Records

*<This section will be filled out as this journey's tasks pass through design>*

## Possible Future Enhancements

* Use Recommendations API (e.g., `gcloud recommender`) to routinely check for IAM over-scoping
* Use inspec.io or other auditing tool to verify the default compute account isn't in use
