### ISSUE TITLE
(Journey) SJ18: Authenticate End Users

### ISSUE THREAD

**Issue by grayside** [GoogleCloudPlatform/emblem#46]
## Description

As an application developer, in order to authenticate contributors and campaign owners, I want to know the easiest path to implement and operate a registration and user authentication system.

## Phase 1 Requirements

* [x] Users visiting the webapp have a registration and login/logout flow
* [x] Content API has a basis of trust that user actions are authorized.
* [x] If "real demo users" engage with Emblem, there is no risk of PII risk from our system

## Related Decision Records

#117: Choose an authorization option for the website

## Possible Future Enhancements

TBD
